/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chuanonly_bubble_core_PlayerThread_PlayerListener */

#ifndef _Included_com_chuanonly_bubble_core_PlayerThread_PlayerListener
#define _Included_com_chuanonly_bubble_core_PlayerThread_PlayerListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
